stick django version to 1.8
Avoiding below error:
django.db.utils.ProgrammingError: relation "patchwork_state" does not exist
LINE 1: ...dering", "patchwork_state"."action_required" FROM "patchwork...